"""更新report名稱

Revision ID: 3334e47b0b6a
Revises: 9d48c2f32e85
Create Date: 2025-06-01 16:17:56.804464

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3334e47b0b6a'
down_revision = '9d48c2f32e85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reviewer_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('report_ibfk_5', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['reviewer_id'], ['id'])
        batch_op.drop_column('reviewed_by')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reviewed_by', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('report_ibfk_5', 'users', ['reviewed_by'], ['id'])
        batch_op.drop_column('reviewer_id')

    # ### end Alembic commands ###
