"""post/comment 的 reaction 加上 ondelete=cascade

Revision ID: 357f25db7e4a
Revises: fef30e7c6d40
Create Date: 2025-06-02 17:00:07.047747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '357f25db7e4a'
down_revision = 'fef30e7c6d40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reactions', schema=None) as batch_op:
        batch_op.drop_constraint('reactions_ibfk_1', type_='foreignkey')
        batch_op.drop_constraint('reactions_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'comments', ['comment_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'posts', ['post_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reactions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('reactions_ibfk_2', 'posts', ['post_id'], ['id'])
        batch_op.create_foreign_key('reactions_ibfk_1', 'comments', ['comment_id'], ['id'])

    # ### end Alembic commands ###
