"""新增歷史紀錄 models

Revision ID: 51381ee10d25
Revises: fe3d42c8ca02
Create Date: 2025-05-31 23:31:34.922574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51381ee10d25'
down_revision = 'fe3d42c8ca02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post__edit__history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('editor_id', sa.Integer(), nullable=False),
    sa.Column('original_title', sa.String(length=255), nullable=True),
    sa.Column('original_content', sa.Text(), nullable=False),
    sa.Column('edited_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['editor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comment__edit__history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.Column('editor_id', sa.Integer(), nullable=False),
    sa.Column('original_content', sa.Text(), nullable=False),
    sa.Column('edited_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], ),
    sa.ForeignKeyConstraint(['editor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment__edit__history')
    op.drop_table('post__edit__history')
    # ### end Alembic commands ###
