"""Add category and note to appointments

Revision ID: 67c3e4a30f71
Revises: 6bdc6fe4815f
Create Date: 2025-06-04 22:08:27.827669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67c3e4a30f71'
down_revision = '6bdc6fe4815f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('note', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_column('note')
        batch_op.drop_column('category')

    # ### end Alembic commands ###
