"""更新user扣除分數定義

Revision ID: 6e260bc58744
Revises: 3334e47b0b6a
Create Date: 2025-06-01 16:51:30.808685

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6e260bc58744'
down_revision = '3334e47b0b6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('points',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('points',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
