"""修改論文月份變數類型

Revision ID: a4919680e7cd
Revises: cc395962952c
Create Date: 2025-06-03 14:46:06.146327

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a4919680e7cd'
down_revision = 'cc395962952c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher_papers', schema=None) as batch_op:
        batch_op.alter_column('year',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=7),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher_papers', schema=None) as batch_op:
        batch_op.alter_column('year',
               existing_type=sa.String(length=7),
               type_=mysql.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
