"""新增user分數跟封鎖欄位

Revision ID: c4e3fd4f655e
Revises: 51381ee10d25
Create Date: 2025-06-01 01:21:59.450067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4e3fd4f655e'
down_revision = '51381ee10d25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('points', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_suspended', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_suspended')
        batch_op.drop_column('points')

    # ### end Alembic commands ###
