"""新增文章與留言的編輯歷史紀錄

Revision ID: fef30e7c6d40
Revises: 6e260bc58744
Create Date: 2025-06-02 16:30:48.452021

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fef30e7c6d40'
down_revision = '6e260bc58744'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_edit_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('editor_id', sa.Integer(), nullable=False),
    sa.Column('original_title', sa.String(length=255), nullable=True),
    sa.Column('original_content', sa.Text(), nullable=False),
    sa.Column('edited_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['editor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comment_edit_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.Column('editor_id', sa.Integer(), nullable=False),
    sa.Column('original_content', sa.Text(), nullable=False),
    sa.Column('edited_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], ),
    sa.ForeignKeyConstraint(['editor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('comment__edit__history')
    op.drop_table('post__edit__history')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post__edit__history',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('post_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('editor_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('original_title', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('original_content', mysql.TEXT(), nullable=False),
    sa.Column('edited_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['editor_id'], ['users.id'], name='post__edit__history_ibfk_1'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name='post__edit__history_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('comment__edit__history',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('comment_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('editor_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('original_content', mysql.TEXT(), nullable=False),
    sa.Column('edited_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], name='comment__edit__history_ibfk_1'),
    sa.ForeignKeyConstraint(['editor_id'], ['users.id'], name='comment__edit__history_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('comment_edit_history')
    op.drop_table('post_edit_history')
    # ### end Alembic commands ###
